

const teamData = [
  {
    name: "Mumbai Indians(MI)",
    captain: "Hardik Pandya",
    bestPlayer: "Rohit Sharma",
    sologan: "MiPaltan",
    totalSession: 16,
    champions: 5,
    matchWin: "56.68%",
    photoName:"teams/mi.jpg",
  },
  {
    name: "Chennai Super Kings(CSK)",
    captain: "MS Dhoni",
    bestPlayer: "Ravindra jadeja",
    sologan: "WhistlePodu",
    totalSession: 14,
    champions: 5,
    matchWin: "58.96%",
    photoName:"teams/csk.jpg",
  },
  {
    name: "Royal Challengers Bangalore(RCB)",
    captain: "Faf du Plessis",
    bestPlayer: "Virat Kohli",
    sologan: "PlayBold",
    totalSession: 16,
    champions: 0,
    matchWin: "48.73%",
    photoName:"teams/rcb.jpg",
  },
  {
    name: "Kalkata Knight Riders(KKR)",
    captain: "Shreyas lyer",
    bestPlayer: "Rinku Singh",
    sologan: "FanNahiTooFanhain",
    totalSession: 16,
    champions: 2,
    matchWin: "51.05%",
    photoName:"teams/kkr.jpg",
  },
  {
    name: "Gujarat Titans(GJ)",
    captain: "Shubham Gill",
    bestPlayer: "Kane Williamson",
    sologan: "aavaDe",
    totalSession: 2,
    champions: 1,
    matchWin: "51.05%",
    photoName:"teams/kkr.jpg",
  },
  {
    name: "Delhi Capitals(DC)",
    captain: "Rishab Pant",
    bestPlayer: "Kuldeep Yadav",
    totalSession: 16,
    champions: 0,
    matchWin: "45.33%",
    photoName:"teams/dc.jpg",
  },
  {
    name: "Rajasthan Royals(RR)",
    captain: "Sanju Samson",
    bestPlayer: "yashasvi Jaiswal",
    sologan: "HallaBol",
    totalSession: 14,
    champions: 1,
    matchWin: "50.24%",
    photoName:"teams/dc.jpg",
  },
  {
    name: "Sunrisers Hyderabad(SRH)",
    captain: "Pat Cummins",
    bestPlayer: "Bhuvneshwar Kumar",
    sologan: "OrangeArmy",
    totalSession: 10,
    champions: 1,
    matchWin: "48.49%",
    photoName:"teams/srh.jpg",
  },
  {
    name: "Punjab Kings(PB)",
    captain: "Shikhar Dhawan",
    bestPlayer: "Liam Livingstone",
    sologan: "SaddaPunjab",
    totalSession: 16,
    champions: 0,
    matchWin: "45.68%",
    photoName:"teams/pb.jpg",
  },
  {
    name: "Lucknow Super Giants(LSG)",
    captain: "KL Rahul",
    bestPlayer: "Nicholas Pooran",
    sologan: "GazabAndaaz",
    totalSession: 2,
    champions: 0,
    matchWin: "58.62%",
    photoName:"teams/lsg.jpg",
  },
  
]

export default App
